
package com.example.chat.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ChatService", targetNamespace = "http://chat.example.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ChatService {


    /**
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getMessages", targetNamespace = "http://chat.example.com/", className = "com.example.chat.client.GetMessages")
    @ResponseWrapper(localName = "getMessagesResponse", targetNamespace = "http://chat.example.com/", className = "com.example.chat.client.GetMessagesResponse")
    @Action(input = "http://chat.example.com/ChatService/getMessagesRequest", output = "http://chat.example.com/ChatService/getMessagesResponse")
    public List<String> getMessages();

    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "sendMessage", targetNamespace = "http://chat.example.com/", className = "com.example.chat.client.SendMessage")
    @ResponseWrapper(localName = "sendMessageResponse", targetNamespace = "http://chat.example.com/", className = "com.example.chat.client.SendMessageResponse")
    @Action(input = "http://chat.example.com/ChatService/sendMessageRequest", output = "http://chat.example.com/ChatService/sendMessageResponse")
    public void sendMessage(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

}
