
package com.example.chat.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "ChatServiceImplService", targetNamespace = "http://chat.example.com/", wsdlLocation = "http://localhost:8080/chat?wsdl")
public class ChatServiceImplService
    extends Service
{

    private final static URL CHATSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CHATSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CHATSERVICEIMPLSERVICE_QNAME = new QName("http://chat.example.com/", "ChatServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8080/chat?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CHATSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CHATSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public ChatServiceImplService() {
        super(__getWsdlLocation(), CHATSERVICEIMPLSERVICE_QNAME);
    }

    public ChatServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CHATSERVICEIMPLSERVICE_QNAME, features);
    }

    public ChatServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CHATSERVICEIMPLSERVICE_QNAME);
    }

    public ChatServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CHATSERVICEIMPLSERVICE_QNAME, features);
    }

    public ChatServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ChatServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ChatService
     */
    @WebEndpoint(name = "ChatServiceImplPort")
    public ChatService getChatServiceImplPort() {
        return super.getPort(new QName("http://chat.example.com/", "ChatServiceImplPort"), ChatService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ChatService
     */
    @WebEndpoint(name = "ChatServiceImplPort")
    public ChatService getChatServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://chat.example.com/", "ChatServiceImplPort"), ChatService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CHATSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CHATSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CHATSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
